### ISSUE TITLE
bug: compose/enviroment.sh does not work for podman

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ioc-template#20]
That is because it sets an alias docker=podman and then tries to use it.

Fix:

- still set the alias
- but also set an env variable docker=docker or docker=podman
- change command line that creates the network to $docker from docker
(same as we already do in template/build)

ALSO

alias ec='docker compose'
should be 
alias dc='docker compose'

**Comment by gilesknap** [comment]
Propogate this change to ioc-adsimdetector and release as 4.0.1

**Comment by marcelldls** [comment]
I believe works on our diamond workstations because by default we have alias expansion enabled:
```
[esq51579@pc0146 ~]$ [ "$(shopt -p expand_aliases)" == "shopt -s expand_aliases" ] && echo "Enabled" || echo "Disabled"
Enabled
```
However it failed on a training laptop, we should probably not rely on alias expansion in a script
