### ISSUE TITLE
Consider new version number scheme

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ioc-template#74]
Now that we have a template project for beamline/accelerator repositories and for generic IOCs there is a possibility for a new version numbering scheme. I assert that the following projects could all track each other's major,minor version numbers to indicate compatibility:

- ec-services-template
- ioc-template
- ec-helm-charts
- edge-containers-cli
- epics-containers.github.io

There is some inter-dependency between all of these. Every time a make a major change I need to update them all in tandem. 

The remaining thing is ibek which could join the team or have its own version scheme because ioc-template determines which version of ibek gets included into generic IOCs.

I already made ec-helm-charts and ec-services-template track each other in the last refresh.

Does this make sense? If we do this I think we should turn on versioning of the documentation repo (I'm kinda surprised that copierifyihng it did not already make that happen)

@coretl @GDYendell @marcelldls : thoughts?

**Comment by gilesknap** [comment]
The great thing is, now that we have copier - you can look at a generic IOC and discover which version of the template it has been updated to (likewise for beamline/accelerator)

**Comment by gilesknap** [comment]
The other reason I'd like to do this is:-

- ioc-template version 2024.2.3 was a major breaking change version. But there is no visibility of that from the versioning scheme.

**Comment by gilesknap** [comment]
I propose all of these projects get reset to 1.0 (probably also need to delete old tags?)

**Comment by coretl** [comment]
SemVer for the template and structures probably makes sense, I think CalVer makes sense for generic iocs and ec-services repos, but it's probably not that appropriate for everything else.

Not worried about the first version number being 3.0, that's reasonable

**Comment by gilesknap** [comment]
@coretl all good - that is exactly my thinking.

**Comment by GDYendell** [comment]
Do users need to know what versions of the other repos that the templates are compatible with, or do the templates define their own dependencies and always just work (even if newer dependency versions are released)? If the latter than CalVer seems fine.

I think it only makes sense to use the same SemVer version for these different things if the end user is expected to pull the correct versions together into a third party application and needs to know which versions are compatible. If the end user just sees an application and templates that are always consistent then it doesn't seem necessary.

If it is necessary then I think only the major version should be coupled. So if there is a breaking change, everything has the major version bumped up to show compatibility, and then the minor and patch versions of can diverge again without having to worry inter dependencies until there is another breaking change.

**Comment by gilesknap** [comment]
Been chatting to Gary about this.

Maybe we should also version ibek and ibek-support together too? (separate to the above versioning)

If you want to get a newish version of ibek then how do you pick an ibek-support commit to go with it ? this requires semver to be possible.

This problem is quite nuanced and is making me queasy. Let's have a whiteboarding session on this sometime next week. I'll put together a list of interdependencies to bring to the meeting.

**Comment by gilesknap** [comment]
OK here is the dependency graph I came up with after a few minutes thought.
https://link.excalidraw.com/l/7igwo1LrqWY/9nOEtA8XPSD
At first I thought this was terrifying but in fact all changes flow from two main places:

- ibek
- helm charts

But I'm not sure the diagram is complete yet.

**Comment by gilesknap** [comment]
I've updated the diagram this morning to group repositories into shared major version number groups.

- individual beamlines / generic IOCs
  - DateVer
- from inside the container: ibek SemVer 
  - ibek
  - ibek support
- from outside the container: ec Semver
  - all other repos 

ioc-template is really inside the container, but  i included it with the larger group because it can bridge the two groups via its requirements.txt that specifies an ibek version.

**Comment by GDYendell** [comment]
> ioc-template is really inside the container, but i included it with the larger group because it can bridge the two groups via its requirements.txt that specifies an ibek version.

The main thing is will the ioc-template version track the ec major version?

**Comment by gilesknap** [comment]
@GDYendell yes that is the plan. The level to which each repo is related to every other is hard to quantify, I've tried to put the relevant features that affect inter dependency inside each box.

It feels like ibek and ibek support are relatively isolated from the rest and deserve a separate version scheme.

I think I'll try living with this arrangement and see what happens.

**Comment by gilesknap** [comment]
We are now using the new version number scheme and I will be writing an epics containers version manifesto this week.
