### ISSUE TITLE
 Raison  to use ENTRYPOINT instead of CMD?

### ISSUE THREAD

**Issue by amichelotti** [epics-containers/ioc-template#81]
For debug raisons (i.e. a start.sh that fails) I would prefer to use CMD instead of ENTRYPOINT that allows to be overridden by docker run .... bash

**Comment by gilesknap** [comment]
I can't think of a good reason to use ENTRYPOINT at the moment and agree that CMD would be more convenient (even though  i have got quite quick at typing `--entrypoint bash` !!).

Will make this change in the next release.

**Comment by gilesknap** [comment]
This is implemented in template 3.4.0 and makes things easier.
